# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField()),
                ('content', models.CharField(blank=True, max_length=250)),
                ('author', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
